'use strict';

module.exports = {
    TICK_MS:        50,
    MAX_PLAYERS:    8,
    MIN_COMBATANTS: 4,
    MAP_SIZE:       1100,
    GRAVITY:        0.014 * 2.5,
    BALL_SPEED:     7.5 * 2.5,
    BALL_Y0:        0.18 * 2.5,
    HIT_RADIUS:     10,
    SHIP_TYPES: {
        sloop: {
            maxSpeed:    0.30 * 2.5,
            turnRate:    0.0012 * 2.5,
            maxHp:       4,
            cannonCount: 3,
            scale:       0.45,
            label:       'Sloop',
            desc:        'Fast, light. Best for capture missions.',
        },
        frigate: {
            maxSpeed:    0.22 * 2.5,
            turnRate:    0.0008 * 2.5,
            maxHp:       7,
            cannonCount: 7,
            scale:       0.6,
            label:       'Frigate',
            desc:        'Balanced. The classic broadside warship.',
        },
        sotl: {
            maxSpeed:    0.14 * 2.5,
            turnRate:    0.0005 * 2.5,
            maxHp:       12,
            cannonCount: 12,
            scale:       0.8,
            label:       'Ship of the Line',
            desc:        'Slow but devastating. Heavy broadside firepower.',
        },
        capital: {
            maxSpeed:    0.08 * 2.5,
            turnRate:    0.0003 * 2.5,
            maxHp:       25,
            cannonCount: 14,
            scale:       1.0,
            label:       'Capital Ship',
            desc:        'The flagship. Sink her to win.',
        },
    },
    SAIL_COLOURS: [
        ['Ivory',   '#f5f0e0'],
        ['Crimson', '#cc2222'],
        ['Ocean',   '#2255aa'],
        ['Midnight','#1a1a3a'],
        ['Gold',    '#d4a017'],
        ['Forest',  '#2a5e2a'],
        ['Obsidian','#222222'],
        ['Blood',   '#8b0000'],
    ],
    HULL_COLOURS: [
        ['Oak',    '#5D4037'],
        ['Ebony',  '#2c1a0e'],
        ['Coral',  '#a05020'],
        ['Slate',  '#445566'],
    ],
    MODES: {
        dm:      { label: 'Deathmatch',           scoreLabel: 'Kills' },
        ctf:     { label: 'Capture the Flag',     scoreLabel: 'Captures' },
        capital: { label: 'Sink the Capital Ship', scoreLabel: 'Damage' },
    },
    DURATIONS: { '3m': 180, '5m': 300, '10m': 600 },
    CTF_FLAG_CAPTURE_R: 18,
    CTF_BASE_R:         30,
    TITLES: ['Captain','Admiral','Commodore','Commander','Rear-Admiral','Vice-Admiral','Ensign','Boatswain'],
};
